version: '3.8'
services:
  rag_pipeline:
    build:
      context: .
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./storage:/app/storage
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
