version: '3.8'
services:
  rag_pipeline:
    build:
      context: .
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMA_PATH=/app/storage/chroma.sqlite3
      - API_HOST=0.0.0.0
      - API_PORT=8000
volumes:
  storage: